import esbuild from 'esbuild';
import process from 'process';
import { fileURLToPath } from 'url';
import path from 'path';
import fs from 'fs';
import 'dotenv/config';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const TEST_VAULT_PATH = process.env.OBSIDIAN_VAULT_PATH || null;

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const outputDir = path.join(__dirname, 'marginalia');

// 确保输出目录存在
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir);
}

// 复制文件到输出目录（dist）
function copyFiles() {
  const filesToCopy = [
    path.join(__dirname, 'manifest.json'),
    path.join(__dirname, 'styles.css')
  ];

  filesToCopy.forEach(file => {
    if (fs.existsSync(file)) {
      const fileName = path.basename(file);
      const dest = path.join(outputDir, fileName);
      fs.copyFileSync(file, dest);
      console.log(`[Build] Copied ${fileName} to output dir`);
    }
  });
}

const copyToVaultPlugin = {
  name: 'copyToVaultPlugin',
  setup(build) {
    build.onEnd(() => {
      // 1. 先判断是否有路径配置
      if (!TEST_VAULT_PATH) {
        // 如果没有配置，直接跳过
        console.log('--------------------------------------------------');
        console.log('Note: No OBSIDIAN_VAULT_PATH configured in .env');
        console.log('Skipping copy to Obsidian vault.');
        console.log('--------------------------------------------------');
        return;
      }

      try {
        // 2. 确保目标文件夹存在
        if (!fs.existsSync(TEST_VAULT_PATH)) {
          fs.mkdirSync(TEST_VAULT_PATH, { recursive: true });
          console.log(`Created directory: ${TEST_VAULT_PATH}`);
        }

        // 3. 需要复制的核心文件
        const filesToDeploy = [
          path.join(outputDir, 'main.js'),
          path.join(outputDir, 'manifest.json'),
          path.join(outputDir, 'styles.css')
        ];

        filesToDeploy.forEach(file => {
          if (fs.existsSync(file)) {
            const fileName = path.basename(file);
            const dest = path.join(TEST_VAULT_PATH, fileName);
            fs.copyFileSync(file, dest);
            console.log(`[Deploy] Copied ${fileName} to vault!`);
          }
        });
        
        console.log('\x1b[32m[Success] Plugin deployed to Obsidian!\x1b[0m');

      } catch (error) {
        console.error('\x1b[31m[Error] Copy failed:\x1b[0m', error.message);
      }
    });
  }
};

esbuild.build({
  banner: { js: banner },
  entryPoints: [path.join(__dirname, 'src', 'main.ts')],
  bundle: true,
  external: ['obsidian'],
  format: 'cjs',
  watch: !prod,
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: path.join(outputDir, 'main.js'),
  plugins: [copyToVaultPlugin],
}).then(() => {
  copyFiles();
  // 清理逻辑...
  const rootMainJs = path.join(__dirname, 'main.js');
  if (fs.existsSync(rootMainJs)) fs.unlinkSync(rootMainJs);
}).catch(() => process.exit(1));