import esbuild from 'esbuild';
import process from 'process';
import { fileURLToPath } from 'url';
import path from 'path';
import fs from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// 定义目标 Obsidian 插件目录路径
const TEST_VAULT_PATH = 'D:\\Vault\\ObsidianPluginsTestVault\\.obsidian\\plugins\\marginalia';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const outputDir = path.join(__dirname, 'marginalia');

// 确保输出目录存在
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir);
}

// 复制文件到输出目录
function copyFiles() {
  const filesToCopy = [
    path.join(__dirname, 'manifest.json'),
    path.join(__dirname, 'styles.css')
  ];

  filesToCopy.forEach(file => {
    const fileName = path.basename(file);
    const dest = path.join(outputDir, fileName);
    fs.copyFileSync(file, dest);
    console.log(`Copied ${fileName} to ${outputDir}`);
  });
}

// 复制到 Obsidian 插件目录的自定义插件
const copyToVaultPlugin = {
  name: 'copyToVaultPlugin',
  setup(build) {
    build.onEnd(() => {
      try {
        // 确保目标文件夹存在
        if (!fs.existsSync(TEST_VAULT_PATH)) {
          fs.mkdirSync(TEST_VAULT_PATH, { recursive: true });
          console.log(`Created directory: ${TEST_VAULT_PATH}`);
        }

        // 需要复制的核心文件
        const filesToDeploy = [
          path.join(outputDir, 'main.js'),
          path.join(outputDir, 'manifest.json'),
          path.join(outputDir, 'styles.css')
        ];

        // 复制文件到 Obsidian 插件目录
        filesToDeploy.forEach(file => {
          if (fs.existsSync(file)) {
            const fileName = path.basename(file);
            const dest = path.join(TEST_VAULT_PATH, fileName);
            fs.copyFileSync(file, dest);
            console.log(`Copied ${fileName} to vault`);
          } else {
            console.error(`File not found: ${file}`);
          }
        });

        // 打印成功消息
        console.log('\x1b[32m[Deploy] Files copied to vault!\x1b[0m');
      } catch (error) {
        console.error('\x1b[31mError copying files to vault:\x1b[0m', error.message);
      }
    });
  }
};

esbuild.build({
  banner: { js: banner },
  entryPoints: [path.join(__dirname, 'src', 'main.ts')],
  bundle: true,
  external: ['obsidian'],
  format: 'cjs',
  watch: !prod,
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: path.join(outputDir, 'main.js'),
  plugins: [copyToVaultPlugin],
}).then(() => {
  // 构建完成后复制文件
  copyFiles();
  
  // 删除根目录下的 main.js（如果存在）
  const rootMainJs = path.join(__dirname, 'main.js');
  if (fs.existsSync(rootMainJs)) {
    fs.unlinkSync(rootMainJs);
    console.log('Deleted root main.js file');
  }
}).catch(() => process.exit(1));
